name: test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '>=3.6'
    - name: deps
      run: |
        pip install -e .
        pip install pytest pylint
    - name: lint
      run: pylint -E oflex
    - name: test
      run: pytest
